### ISSUE TITLE
Compiler generates incorrect error when using 'whereis()' if variable optimization is set to yes

### ISSUE THREAD

**Issue by RobJansen62** [jallib/jalv2compiler#1]
### Problem
'whereis()' cannot be used on a constant. If, however, 'whereis()' is used on a variable and the compiler optimization to reduce variables is set to yes then this error is incorrectly generated. 
Compiler: JALV25

### Sample program:
pragma warn all yes
pragma opt variable_reduce yes -- This will result in an error using whereis!!
;pragma opt variable_reduce no   -- This will prevent the error.
include 16f1825              -- target PICmicro

var volatile word mem_pointer1_address
var volatile byte my_address
var volatile byte my_dest at my_address

Forever Loop
  -- This does not work when reduce variables is set to yes.
  mem_pointer1_address = whereis(my_address)
End Loop

### Result from the compiler:
error: Cannot use whereis() on a constant

**Comment by mattschinkel** [comment]
Although whereis() is not a constant, it should be. I previously requested this feature enhancement. Is this possible? The compiler knows the locations of variables during compile.

**Comment by RobJansen62** [comment]
The issue mentioned in the original description is fixed in jalv25r1. For the feature request a new issue is created, see: https://github.com/jallib/jalv2compiler/issues/5
