### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by robhamerling** [jallib/jalv2compiler#15]
When compiling the program below the compiler throws a 'segmentation fault'.

Linux Mint 20.0; compiler jalv2-x86-64 (64 bits Linux): jal jalv25r4 (compiled Nov 19 2020)

[18f27q43_128k.zip](https://github.com/jallib/jalv2compiler/files/5610378/18f27q43_128k.zip)

**Comment by RobJansen62** [comment]
The compiler entered an endless loop when assigning an integer value to a float variable. Fixed in jalv25r4 with help of Kyle.
