### ISSUE TITLE
curious warnings

### ISSUE THREAD

**Issue by robhamerling** [jallib/jalv2compiler#16]
The program in the mentioned ZIP-file produces the console output below. After removing one single 'pragma inline' (for example on line 44 and leaving everything else the same)  the warnings are gone.
Linux Mint 20.0 64-bits

[18f27q43_128k.zip](https://github.com/jallib/jalv2compiler/files/5610845/18f27q43_128k.zip)

rob@XH110G ~/jal_128k $ ./jalv2-x86-64 -no-codfile  18f27q43_128k.jal
jal jalv25r4 (compiled Nov 19 2020)
generating p-code
51561 tokens, 440506 chars; 8130 lines; 3 files
generating PIC code pass 1[18f27q43_128k.zip](https://github.com/jallib/jalv2compiler/files/5610845/18f27q43_128k.zip)
generating PIC code pass 2
18f27q43_128k.jal:82: warning: data error at 0x00000028 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x0000002c (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x00000030 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x00000042 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x00000046 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x00000058 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x0000007e (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x00000082 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x00000086 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x00000098 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x0000009c (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x000000ae (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x000000d4 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x000000d8 (got ffff expected ffff)
18f27q43_128k.jal:82: warning: data error at 0x000000ea (got ffff expected ffff)
1242 data accesses checked, 15 errors
25 skips checked, 0 errors
writing result
28 (ffff + 0): {_pic_temp[i---1]}
2c (ffff + 0): {_pic_temp[i---1]}
30 (ffff + 0): {_pic_temp[i---1]}
42 (ffff + 0): {_pic_temp[i---1]}
46 (ffff + 0): {_pic_temp[i---1]}
58 (ffff + 0): {_pic_temp[i---1]}
7e (ffff + 0): {_pic_temp[i---1]}
82 (ffff + 0): {_pic_temp[i---1]}
86 (ffff + 0): {_pic_temp[i---1]}
98 (ffff + 0): {_pic_temp[i---1]}
9c (ffff + 0): {_pic_temp[i---1]}
ae (ffff + 0): {_pic_temp[i---1]}
d4 (ffff + 0): {_pic_temp[i---1]}
d8 (ffff + 0): {_pic_temp[i---1]}
ea (ffff + 0): {_pic_temp[i---1]}
Code area: 10016 of 131072 used (bytes)
Data area: 146 of 8448 used
Software stack available: 8301 bytes
Hardware stack depth 2 of 128
0 errors, 15 warnings

**Comment by kyleyork2** [comment]
looks like you need simply to change the type of variable_base_t from `unsigned short' to `unsigned'

**Comment by RobJansen62** [comment]
I tried that but is does not solve the problem. Output is then as follows:

jal jalv25r4 (compiled Dec 10 2020)
generating p-code
51561 tokens, 440506 chars; 8130 lines; 3 files
generating PIC code pass 1
generating PIC code pass 2
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000028 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x0000002c (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000032 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000038 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x0000004c (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000050 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000056 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x0000006a (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x0000006e (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000096 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x0000009a (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x000000a0 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x000000a6 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x000000ba (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x000000be (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x000000c4 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x000000d8 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x000000dc (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000104 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000108 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x0000010e (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000122 (got ffff expected ffffffff)
D:\pic\compiler\test\Issue#16\18f27q43_128k.jal:82: warning: data error at 0x00000126 (got ffff expected ffffffff)
1250 data accesses checked, 23 errors
25 skips checked, 0 errors
writing result
28 (ffffffff + 0): {_pic_temp[i---1]}
2c (ffffffff + 0): {_pic_temp[i---1]}
32 (ffffffff + 0): {_pic_temp[i---1]}
38 (ffffffff + 0): {_pic_temp[i---1]}
4c (ffffffff + 0): {_pic_temp[i---1]}
50 (ffffffff + 0): {_pic_temp[i---1]}
56 (ffffffff + 0): {_pic_temp[i---1]}
6a (ffffffff + 0): {_pic_temp[i---1]}
6e (ffffffff + 0): {_pic_temp[i---1]}
96 (ffffffff + 0): {_pic_temp[i---1]}
9a (ffffffff + 0): {_pic_temp[i---1]}
a0 (ffffffff + 0): {_pic_temp[i---1]}
a6 (ffffffff + 0): {_pic_temp[i---1]}
ba (ffffffff + 0): {_pic_temp[i---1]}
be (ffffffff + 0): {_pic_temp[i---1]}
c4 (ffffffff + 0): {_pic_temp[i---1]}
d8 (ffffffff + 0): {_pic_temp[i---1]}
dc (ffffffff + 0): {_pic_temp[i---1]}
104 (ffffffff + 0): {_pic_temp[i---1]}
108 (ffffffff + 0): {_pic_temp[i---1]}
10e (ffffffff + 0): {_pic_temp[i---1]}
122 (ffffffff + 0): {_pic_temp[i---1]}
126 (ffffffff + 0): {_pic_temp[i---1]}
Code area: 10076 of 131072 used (bytes)
Data area: 146 of 8448 used
Software stack available: 8301 bytes
Hardware stack depth 2 of 128
0 errors, 23 warnings

**Comment by RobJansen62** [comment]
It only happens when using floats and when using pragma inline is used in both functions. If float is replaced by word or if one pragma inline is removed the problem does not occur.

**Comment by RobJansen62** [comment]
Fixed in jalv25r4.
